url: https://esmasoft.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: EsmaSoft Consulting
email: nerobianchi@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Erdem OZDEMIR
  pic: 2
  position: Senior Software Developer / Owner
  social:
    - title: twitter
      url: https://twitter.com/nerobianchi
    - title: medium
      url: https://medium.com/@nerobianchi
    - title: github
      url: https://github.com/nerobianchi
    - title: linkedin
      url: https://www.linkedin.com/in/erdemozdemir/


# Postal address (add as many lines as necessary)
address:
  - line: London
  - line: UK

# Build settings
markdown: kramdown
permalink: pretty